"""
utils/__init__.py
Utility functions and helpers for the Universal Data Science Toolkit.
"""

from .cli import (ArgumentValidator, CLIApplication, CLIParser,
                  ColoredFormatter, CommandHandler, ConfigArgumentParser,
                  ProgressBar, create_cli_app, create_cli_command,
                  format_bytes, format_duration, print_error, print_info,
                  print_success, print_summary, print_table, print_warning,
                  prompt_choice, run_command, spinner)
from .file_io import (CheckpointManager, ConfigLoader, DataCache, DataReader,
                      DataWriter, FileHandler, ModelSerializer, create_archive,
                      load_config, load_object, save_config, save_object)
from .logging import (ColoredFormatter, ExperimentLogger, LogConfig, LogFormat,
                      ProgressLogger, StructuredFormatter, StructuredLogger,
                      get_logger, log_context, log_exceptions,
                      log_execution_time, log_memory_usage, redirect_warnings,
                      setup_logger)
from .parallel import (BackendType, ChunkProcessor, DistributedProcessor,
                       ParallelBatch, ParallelConfig, ParallelProcessor,
                       ProgressParallel, SharedMemoryArray,
                       chunked_parallel_process, get_n_jobs, parallel_apply,
                       parallel_groupby_apply, parallel_map, parallel_read_csv,
                       parallel_save_partitions)

__all__ = [
    # File I/O
    "FileHandler",
    "DataReader",
    "DataWriter",
    "ModelSerializer",
    "ConfigLoader",
    "DataCache",
    "CheckpointManager",
    "save_object",
    "load_object",
    "save_config",
    "load_config",
    "create_archive",
    # Parallel processing
    "BackendType",
    "ParallelProcessor",
    "ParallelConfig",
    "ParallelBatch",
    "ProgressParallel",
    "ChunkProcessor",
    "DistributedProcessor",
    "SharedMemoryArray",
    "get_n_jobs",
    "parallel_apply",
    "parallel_map",
    "parallel_groupby_apply",
    "chunked_parallel_process",
    "parallel_read_csv",
    "parallel_save_partitions",
    # CLI utilities
    "ColoredFormatter",
    "CLIParser",
    "CLIApplication",
    "CommandHandler",
    "ArgumentValidator",
    "ConfigArgumentParser",
    "ProgressBar",
    "create_cli_app",
    "run_command",
    "spinner",
    "prompt_choice",
    "print_table",
    "print_summary",
    "create_cli_command",
    "format_bytes",
    "format_duration",
    "print_error",
    "print_warning",
    "print_success",
    "print_info",
    # Logging
    "LogFormat",
    "LogConfig",
    "ColoredFormatter",
    "StructuredFormatter",
    "StructuredLogger",
    "ProgressLogger",
    "ExperimentLogger",
    "log_execution_time",
    "log_memory_usage",
    "log_context",
    "log_exceptions",
    "redirect_warnings",
    "setup_logger",
    "get_logger",
]

__version__ = "1.0.0"
